spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ashok
    url: jdbc:h2:mem:synechrondb
    username: ashok
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
      
plani-api:
  messages:
   planSaveSucc: Plan Saved Successfully
   planSaveFail: Plan Saved Fail
   planUpdateSucc: Plan Updated Successfuly
   planUpdateFail: Plan Updated Fail
   planDeleteSucc: Plan Delete Success
   planDeleteFail: Plan Delete Failed 
   planStatusChnageSucc: Plan Status Chnaged Succ
   planStatusChnageFail: Plan Status Chnaged Fail
